## Tensors 101

In [1]:
import numpy as np
import torch

Row vector  

In [2]:
tensor_row = torch.tensor([1, 2, 3])

Column row

In [3]:
tensor_col = torch.tensor([[1], [2], [3]])

In [4]:
tensor_row

tensor([1, 2, 3])

In [5]:
tensor_col

tensor([[1],
        [2],
        [3]])

Going from numpy to torchs

In [6]:
vector_row=np.array([1, 0, 1])
tensor_row=torch.from_numpy(vector_row)

How to create sparse tensors   

In [7]:
temp=np.zeros((10, 10))
temp[0:5, 1:3] = 1

tensor = torch.from_numpy(temp)

In [8]:
sparse_tensor=tensor.to_sparse()
sparse_tensor

tensor(indices=tensor([[0, 0, 1, 1, 2, 2, 3, 3, 4, 4],
                       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2]]),
       values=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
       size=(10, 10), nnz=10, dtype=torch.float64, layout=torch.sparse_coo)

In [9]:
tensor

tensor([[0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [10]:
tensor[0:3, 1:2]

tensor([[1.],
        [1.],
        [1.]], dtype=torch.float64)

In [11]:
sparse_tensor[0:3, 1:2]

NotImplementedError: Could not run 'aten::as_strided' with arguments from the 'SparseCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::as_strided' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at /croot/pytorch-select_1700158693612/work/build/aten/src/ATen/RegisterCPU.cpp:31188 [kernel]
Meta: registered at /croot/pytorch-select_1700158693612/work/build/aten/src/ATen/RegisterMeta.cpp:26829 [kernel]
QuantizedCPU: registered at /croot/pytorch-select_1700158693612/work/build/aten/src/ATen/RegisterQuantizedCPU.cpp:944 [kernel]
BackendSelect: fallthrough registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/core/PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/functorch/DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at /croot/pytorch-select_1700158693612/work/build/aten/src/ATen/RegisterFunctionalization_0.cpp:21905 [kernel]
Named: fallthrough registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
Conjugate: fallthrough registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/ConjugateFallback.cpp:21 [kernel]
Negative: fallthrough registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/native/NegateFallback.cpp:23 [kernel]
ZeroTensor: registered at /croot/pytorch-select_1700158693612/work/build/aten/src/ATen/RegisterZeroTensor.cpp:161 [kernel]
ADInplaceOrView: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/ADInplaceOrViewType_0.cpp:4733 [kernel]
AutogradOther: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradCPU: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradCUDA: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradHIP: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradXLA: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradMPS: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradIPU: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradXPU: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradHPU: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradVE: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradLazy: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradMTIA: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradPrivateUse1: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradPrivateUse2: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradPrivateUse3: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradMeta: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
AutogradNestedTensor: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/VariableType_0.cpp:16790 [autograd kernel]
Tracer: registered at /croot/pytorch-select_1700158693612/work/torch/csrc/autograd/generated/TraceType_0.cpp:16725 [kernel]
AutocastCPU: fallthrough registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/autocast_mode.cpp:382 [backend fallback]
AutocastCUDA: fallthrough registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/autocast_mode.cpp:249 [backend fallback]
FuncTorchBatched: registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:714 [kernel]
FuncTorchVmapMode: fallthrough registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/LegacyBatchingRegistrations.cpp:1079 [kernel]
VmapMode: fallthrough registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/functorch/TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/core/PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/functorch/DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/core/PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at /croot/pytorch-select_1700158693612/work/aten/src/ATen/core/PythonFallbackKernel.cpp:157 [backend fallback]


Sliced tensor is still a tensor

In [12]:
tensor[:]

tensor([[0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [13]:
tensor[0, 0]

tensor(0., dtype=torch.float64)

In [14]:
tensor[:, ::-1]

ValueError: step must be greater than zero

In [15]:
tensor.flip(dims=(1,))

tensor([[0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

Describing tensors      


In [16]:
tensor.shape

torch.Size([10, 10])

In [17]:
tensor.dtype

torch.float64

In [18]:
tensor.layout

torch.strided

In [19]:
tensor.device

device(type='cpu')

Tensor operations   


In [20]:
tensor  

tensor([[0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [21]:
tensor * 100

tensor([[  0., 100., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0., 100., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0., 100., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0., 100., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0., 100., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]],
       dtype=torch.float64)

Summaries

In [22]:
tensor.max()

tensor(1., dtype=torch.float64)

In [23]:
tensor.min()

tensor(0., dtype=torch.float64)

In [24]:
tensor.median()

tensor(0., dtype=torch.float64)

Reshaping

In [25]:
tensor.shape

torch.Size([10, 10])

In [26]:
tensor.reshape(100, 1)

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

In [27]:
tensor

tensor([[0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

Tensor manipulation

In [28]:
tensor.T

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [29]:
tensor.mT

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [30]:
small_3d= np.ones((5, 5, 5))
small_3d[0:2, 3:4, 1:4]=0
tensor_3d=torch.from_numpy(small_3d)
tensor_3d

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 0., 0., 0., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 0., 0., 0., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]], dtype=torch.float64)

In [31]:
tensor_3d.T

/tmp/ipykernel_149230/1924630843.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /croot/pytorch-select_1700158693612/work/aten/src/ATen/native/TensorShape.cpp:3614.)
  tensor_3d.T


tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [0., 0., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [0., 0., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [0., 0., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]], dtype=torch.float64)

In [32]:
tensor_3d.mT

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]], dtype=torch.float64)

In [33]:
tensor.flatten()

tensor([0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)

Dot products

In [34]:
tensor_1=torch.tensor([1, 3, 5])
tensor_2=torch.tensor([1, 2, 4])
tensor_1.dot(tensor_2)

tensor(27)

Multiplication

In [35]:
tensor_1 * tensor_2

tensor([ 1,  6, 20])

## Neural Networks

- Neuron: takes an input an multiple it by a parameter or weight, sums it up along some bias then it is feed into an activation function
- Input layer: each unit is an observation for a feature
- Hidden layers: layers that transform the feature values from the input layer into something that is usefull for the targeted class
- Output layer: transform the intermediate inputs into values useful for the task at hand
- Forward propragation
- Back propragation
Weights are tipically initialized either from random sampling from a gaussian or normal uniform distribution.

NN do poorly when they are not scale. Scale your damn data!!

#### Autograd

Autograd: a way to automatically compute and store the gradients used to optimize the parameters of the netowrks after going foward and backwards propragation

Autograd use a directed acyclic graph to keep track of the data and computations used in it. This means you cannot go pytorch->numpy and numpy<-pytorch easily

In [36]:
t= torch.tensor([2.0, 4.0, 6.0], requires_grad=True)

Simulating foward propagation

In [37]:
t_sum= t.sum()

Simulating backward propragation

In [38]:
t_sum.backward()

Gradients

In [39]:
t.grad

tensor([1., 1., 1.])

torch -> numpy

In [40]:
t.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [41]:
t.detach().numpy()

array([2., 4., 6.], dtype=float32)

/!\ this will stop numpy from automatically calculating the gradient /!\

#### Preprocessing for NN

How to scale data that you have `requires_grad=True`

In [42]:
non_scaled_tensor=torch.tensor([[1000.2, 9.32],
                                [-9000.1, -9067.675],
                                [3948.3, -1981.087],
                                [2313.4, -112.674]],
                                requires_grad=True)

In [43]:
non_scaled_tensor

tensor([[ 1000.2000,     9.3200],
        [-9000.0996, -9067.6748],
        [ 3948.3000, -1981.0870],
        [ 2313.3999,  -112.6740]], requires_grad=True)

In [44]:
mean=non_scaled_tensor.mean(0, keepdim=True)
std= non_scaled_tensor.std(0, unbiased=False, keepdim=True)

In [45]:
mean

tensor([[ -434.5499, -2788.0288]], grad_fn=<MeanBackward1>)

In [46]:
std

tensor([[5054.3979, 3710.3838]], grad_fn=<StdBackward0>)

In [47]:
scaled_tensor= (non_scaled_tensor - mean)/std

In [48]:
scaled_tensor

tensor([[ 0.2839,  0.7539],
        [-1.6947, -1.6925],
        [ 0.8671,  0.2175],
        [ 0.5437,  0.7210]], grad_fn=<DivBackward0>)

#### A small example with autograd

In [58]:
x=torch.rand(1, 10, requires_grad=True)
prev_h=torch.rand(1, 20, requires_grad=True)
W_h= torch.rand(20, 20, requires_grad=True)
W_x=torch.rand(20,10, requires_grad=True)
i2h=torch.mm(W_x, x.t())
h2h=torch.mm(W_h, prev_h.t())
next_h= i2h + h2h
next_h= next_h.tanh()
loss= next_h.sum()


In [59]:
loss.backward()

In [60]:
print(W_x.grad, W_h.grad, x.grad, prev_h.grad)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.9191e-08, 1.1251e-07, 2.0231e-07, 5.5796e-08, 6.1820e-08, 1.7643e-07,
         2.7142e-08, 1.5448e-07, 6.0156e-08, 1.6152e-07],
        [2.9757e-07, 3.3753e-07, 6.0694e-07, 1.6739e-07, 1.8546e-07, 5.2930e-07,
         8.1427e-08, 4.6345e-07, 1.8047e-07, 4.8457e-07],
        [4.9595e-08, 5.6255e-08, 1.0116e-07, 2.7898e-08, 3.0910e-08, 8.8216e-08,
         1.3571e-08, 7.7241e-08, 3.0078e-08, 8.0763e-08],
        [9.9191e-08, 1.1251e-07, 2.0231e-07, 5.5796e-08, 6.1820e-08, 1.7643e-07,
         2.7142e-08, 1.5448e-07, 6.0156e-08, 1.6152e-07],
        [7.4393e-07, 8.4382e-07, 1.5174e-06, 4.1847e-07, 4.6365e-07, 1.3232e-06,
         2.0357e-07, 1.1586e-06, 4.5117e-07, 1.2114e-06],
        [2.4798e-07, 2.8127e-07, 5.0578e-07, 1.3949e-07, 1.5455e-07, 4.4108e-07,
         6.7856e-08, 3.8620e-07, 1.5039e-07, 4.0381e-07],
        [0.0000e+00, 0.0000

#### More